Repository LyFl0w/Fracteur, pull requests merged in 2023-05, with the labels that each got.

#26 Update sierpinski.py
  program/fractal/fractal_type/sierpinski.py
Labels: fix

#27 Update sponge_cube.py
  program/fractal/fractal_type/sponge_cube.py
Labels: fix

#28 Features/optimization
  README.md
  program/application.py
  program/fractal/fractal_manger.py
  program/fractal/fractal_type/mandelbrot.py
  program/fractal/fractal_type/sierpinski.py
  program/fractal/fractal_type/sponge_cube.py
  program/prototype/pyramide3d.py
  program/utils/queue_update.py
  requirements.txt
Labels: enhancement, fix

#30 ajout d'un math.py pour des calculs plus rapides
  program/fractal/fractal_type/julia.py
  program/fractal/fractal_type/mandelbrot.py
  program/utils/math.py
Labels: enhancement, fix

#32 Features/interface
  README.md
  program/fractal/fractal_type/julia.py
  program/interface.py
  program/settings/fractal_settings.py
Labels: enhancement

#33 Dev
  README.md
  program/fractal/fractal_type/julia.py
  program/interface.py
  program/settings/fractal_settings.py
Labels: enhancement

#34 suppresion de plusieurs variables de verification d'utilisation de ma…
  program/application.py
  program/prototype/cube3d.py
  program/prototype/pyramide3d.py
Labels: fix

#35 optimisation des calculs des fractals sierpinski et sponge_cube
  program/fractal/fractal_type/sierpinski.py
  program/fractal/fractal_type/sponge_cube.py
Labels: enhancement

#36 Dev
  program/application.py
  program/fractal/fractal_type/sierpinski.py
  program/fractal/fractal_type/sponge_cube.py
  program/prototype/cube3d.py
  program/prototype/pyramide3d.py
Labels: enhancement, fix

#39 Dev
  program/fractal/fractal_manger.py
  program/interface.py
Labels: enhancement, fix

#40 augmentation du nombre d'itération possible
  program/fractal/fractalbase.py
Labels: enhancement

#41 Code annotation
  main.py
  program/application.py
  program/fractal/fractal_manger.py
  program/fractal/fractalbase.py
  program/settings/fractal_settings.py
  program/settings/screen_settings.py
  program/settings/settingsbase.py
  program/utils/json_utils.py
  program/utils/math.py
  program/utils/path.py
  program/utils/queue_update.py
Labels: documentation

#44 Dev
  program/fractal/fractal_manger.py
  program/fractal/fractal_type/mandelbrot.py
  program/interface.py
Labels: fix

#45 Correction doc
  README.md
Labels: documentation

#47 Dev
  README.md
Labels: documentation

#48 Dev
  program/application.py
  program/fractal/fractal_type/julia.py
  program/fractal/fractal_type/mandelbrot.py
  program/fractal/fractal_type/sponge_cube.py
  program/utils/math.py
Labels: enhancement
